Repository grap/grap-odoo-custom, pull requests merged in 2025-03, with the labels that each got.

#443 [REF] Update Copier Update. (2025-03-14)
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .ruff.toml
Labels: bot is merging ⏳, needs review

#437 [FIX] fermente_cooperative_directory: missing facebook icon
  fermente_cooperative_directory/views/view_res_company.xml
Labels: bot is merging ⏳

#438 [IMP] fermente_cooperative_directory: add private data in public dire…
  fermente_cooperative_directory/__manifest__.py
  fermente_cooperative_directory/i18n/fr.po
  fermente_cooperative_directory/models/hr_employee_global.py
  fermente_cooperative_directory/views/view_hr_employee_global.xml
  test-requirements.txt
Labels: bot is merging ⏳

#431 [FIX] mrp_sale_grouped multi-company rule
  mrp_sale_grouped/security/ir_rule.xml
Labels: TO MERGE, bot is merging ⏳

#447 [REF] fermente_hr: remove patriarcat
  fermente_hr/views/view_hr_employee.xml
Labels: TO MERGE, bot is merging ⏳

#445 16.0 ref fermente cooperative directory rem referente
  fermente_cooperative_directory/models/res_company.py
  fermente_cooperative_directory/views/view_res_company.xml
Labels: TO MERGE, bot is merging ⏳

#442 [FIX] fermente_product_category_active: Do not break inheritance mech…
  fermente_product_category_active/models/product_template.py
Labels: TO MERGE, bot is merging ⏳, needs review

#439 [16.0][MIG] grap_theme: Migration to 16.0 (from 12.0)
  fermente_web/README.rst
  fermente_web/__init__.py
  fermente_web/__manifest__.py
  fermente_web/controllers/__init__.py
  fermente_web/controllers/main.py
  fermente_web/readme/CONTRIBUTORS.rst
  fermente_web/readme/DESCRIPTION.rst
  fermente_web/static/description/icon.png
  fermente_web/static/description/login_page.png
  fermente_web/static/description/product_tree.png
  fermente_web/static/src/img/caap.png
  fermente_web/static/src/img/fermente.png
  fermente_web/static/src/img/grap.png
  fermente_web/static/src/img/mache.png
  fermente_web/static/src/img/undefined_database.png
  fermente_web/static/src/scss/fermente_web.scss
  fermente_web/static/src/xml/switch_company_menu.xml
  setup/fermente_web/odoo/addons/fermente_web
  setup/fermente_web/setup.py
Labels: TO MERGE, bot is merging ⏳

#433 [16.0][FIX] mrp_sale_grouped message on wizard
  mrp_sale_grouped/i18n/fr.po
  mrp_sale_grouped/wizard/bom_print_purchase_list_wizard.py
Labels: TO MERGE, bot is merging ⏳

#432 [IMP] fermente_mrp Polish BoM view and Menus
  fermente_mrp/__manifest__.py
  fermente_mrp/i18n/fr.po
  fermente_mrp/views/menu.xml
  fermente_mrp_bom_form_view/__manifest__.py
  fermente_mrp_bom_form_view/i18n/fr.po
  fermente_mrp_bom_form_view/views/view_mrp_bom.xml
  mrp_sale_grouped/__manifest__.py
  mrp_sale_grouped/views/menu.xml
  test-requirements.txt
Labels: TO MERGE, bot is merging ⏳

#444 [16.0][ADD] product_default_route_buy
  product_default_route_buy/README.rst
  product_default_route_buy/__init__.py
  product_default_route_buy/__manifest__.py
  product_default_route_buy/hooks.py
  product_default_route_buy/models/__init__.py
  product_default_route_buy/models/product_template.py
  product_default_route_buy/readme/CONTRIBUTORS.rst
  product_default_route_buy/readme/DESCRIPTION.rst
  product_default_route_buy/static/description/product_purchase_ok.jpeg
  product_default_route_buy/tests/__init__.py
  product_default_route_buy/tests/test_product_template.py
  setup/product_default_route_buy/odoo/addons/product_default_route_buy
  setup/product_default_route_buy/setup.py
Labels: TO MERGE, bot is merging ⏳

#446 [16.0][IMP] fermente_mrp_bom_form_view-Title-characterisation-and-hierarchy
  fermente_mrp_bom_form_view/__init__.py
  fermente_mrp_bom_form_view/__manifest__.py
  fermente_mrp_bom_form_view/i18n/fr.po
  fermente_mrp_bom_form_view/models/__init__.py
  fermente_mrp_bom_form_view/models/mrp_bom.py
  fermente_mrp_bom_form_view/views/view_mrp_bom.xml
Labels: TO MERGE, bot is merging ⏳

#440 [16.0][ADD] product_default_route_mrp [IMP] fermente_mrp
  fermente_mrp/__manifest__.py
  fermente_mrp/data/stock_route.xml
  fermente_mrp/readme/CONTRIBUTORS.rst
  fermente_mrp/readme/DESCRIPTION.rst
  product_default_route_mrp/README.rst
  product_default_route_mrp/__init__.py
  product_default_route_mrp/__manifest__.py
  product_default_route_mrp/hooks.py
  product_default_route_mrp/models/__init__.py
  product_default_route_mrp/models/mrp_bom.py
  product_default_route_mrp/readme/CONTRIBUTORS.rst
  product_default_route_mrp/readme/DESCRIPTION.rst
  product_default_route_mrp/tests/__init__.py
  product_default_route_mrp/tests/test_mrp_bom.py
  setup/product_default_route_mrp/odoo/addons/product_default_route_mrp
  setup/product_default_route_mrp/setup.py
Labels: TO MERGE, bot is merging ⏳

#448 12.0-REF-copier-update-2025-03-27
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
Labels: bot is merging ⏳, needs review
